version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: css222
      POSTGRES_DB: eeg_database
    volumes:
      - ./postgres_schema/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/data
    ports:
      - "5432:5432"

  elt_script:
    build: ./etl
    volumes:
      - ../dataset:/dataset
    depends_on:
      - db
